{ created_at: 'Fri Jun 06 19:27:55 +0000 2014',
  id: 474996124345188350,
  id_str: '474996124345188352',
  text: '@test43523 test test test',
  source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 2499044862,
  in_reply_to_user_id_str: '2499044862',
  in_reply_to_screen_name: 'test43523',
  user: 
   { id: 2515077132,
     id_str: '2515077132',
     name: 'Dylan Yep',
     screen_name: 'DylanYep',
     location: '',
     url: null,
     description: null,
     protected: false,
     followers_count: 0,
     friends_count: 0,
     listed_count: 0,
     created_at: 'Thu May 22 10:30:45 +0000 2014',
     favourites_count: 0,
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     verified: false,
     statuses_count: 2,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     default_profile: true,
     default_profile_image: true,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  favorite_count: 0,
  entities: 
   { hashtags: [],
     symbols: [],
     urls: [],
     user_mentions: [ [Object] ] },
  favorited: false,
  retweeted: false,
  filter_level: 'medium',
  lang: 'et' }